/**
 * Regenerates src/utils/leafletAssets.ts by inlining the installed `leaflet`
 * package's built JS/CSS as string constants. The in-app map (src/utils/mapHtml.ts)
 * embeds these directly into a WebView/iframe's HTML so the map library itself
 * needs no CDN at runtime — only the OpenStreetMap tile requests do, which is
 * unavoidable for any real map.
 *
 * Run after bumping the `leaflet` devDependency version:
 *   npm run vendor:leaflet
 */
import { readFileSync, writeFileSync } from 'node:fs';

const js = readFileSync('node_modules/leaflet/dist/leaflet.js', 'utf8');
const css = readFileSync('node_modules/leaflet/dist/leaflet.css', 'utf8');

const out = `// Auto-generated by scripts/vendor-leaflet.mjs — do not edit by hand.
export const LEAFLET_JS = ${JSON.stringify(js)};

export const LEAFLET_CSS = ${JSON.stringify(css)};
`;

writeFileSync('src/utils/leafletAssets.ts', out);
console.log(`Wrote src/utils/leafletAssets.ts (${out.length} bytes).`);
